// lib/formOptions.ts
// This file is the single source of truth for all dropdown and checkbox options in the profile form.

// --- Education Related ---
export const COUNTRY_OPTIONS = [
    { value: "", label: "Please Select" },
    { value: "Switzerland", label: "Switzerland" },
    { value: "Germany", label: "Germany" },
    { value: "Italy", label: "Italy" },
    { value: "France", label: "France" },
    { value: "Afghanistan", label: "Afghanistan" },
    { value: "Albania", label: "Albania" },
    { value: "Algeria", label: "Algeria" },
    { value: "Andorra", label: "Andorra" },
    { value: "Angola", label: "Angola" },
    { value: "Antigua and Barbuda", label: "Antigua and Barbuda" },
    { value: "Argentina", label: "Argentina" },
    { value: "Armenia", label: "Armenia" },
    { value: "Australia", label: "Australia" },
    { value: "Austria", label: "Austria" },
    { value: "Azerbaijan", label: "Azerbaijan" },
    { value: "Bahamas", label: "Bahamas" },
    { value: "Bahrain", label: "Bahrain" },
    { value: "Bangladesh", label: "Bangladesh" },
    { value: "Barbados", label: "Barbados" },
    { value: "Belarus", label: "Belarus" },
    { value: "Belgium", label: "Belgium" },
    { value: "Belize", label: "Belize" },
    { value: "Benin", label: "Benin" },
    { value: "Bhutan", label: "Bhutan" },
    { value: "Bolivia", label: "Bolivia" },
    { value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina" },
    { value: "Botswana", label: "Botswana" },
    { value: "Brazil", label: "Brazil" },
    { value: "Brunei", label: "Brunei" },
    { value: "Bulgaria", label: "Bulgaria" },
    { value: "Burkina Faso", label: "Burkina Faso" },
    { value: "Burundi", label: "Burundi" },
    { value: "Cabo Verde", label: "Cabo Verde" },
    { value: "Cambodia", label: "Cambodia" },
    { value: "Cameroon", label: "Cameroon" },
    { value: "Canada", label: "Canada" },
    { value: "Central African Republic", label: "Central African Republic" },
    { value: "Chad", label: "Chad" },
    { value: "Chile", label: "Chile" },
    { value: "China", label: "China" },
    { value: "Colombia", label: "Colombia" },
    { value: "Comoros", label: "Comoros" },
    { value: "Congo, Democratic Republic of the", label: "Congo, Democratic Republic of the" },
    { value: "Congo, Republic of the", label: "Congo, Republic of the" },
    { value: "Costa Rica", label: "Costa Rica" },
    { value: "Cote d'Ivoire", label: "Cote d'Ivoire" }, // Note: ' converted to '
    { value: "Croatia", label: "Croatia" },
    { value: "Cuba", label: "Cuba" },
    { value: "Cyprus", label: "Cyprus" },
    { value: "Czech Republic", label: "Czech Republic" },
    { value: "Denmark", label: "Denmark" },
    { value: "Djibouti", label: "Djibouti" },
    { value: "Dominica", label: "Dominica" },
    { value: "Dominican Republic", label: "Dominican Republic" },
    { value: "Ecuador", label: "Ecuador" },
    { value: "Egypt", label: "Egypt" },
    { value: "El Salvador", label: "El Salvador" },
    { value: "Equatorial Guinea", label: "Equatorial Guinea" },
    { value: "Eritrea", label: "Eritrea" },
    { value: "Estonia", label: "Estonia" },
    { value: "Eswatini", label: "Eswatini" },
    { value: "Ethiopia", label: "Ethiopia" },
    { value: "Fiji", label: "Fiji" },
    { value: "Finland", label: "Finland" },
    { value: "Gabon", label: "Gabon" },
    { value: "Gambia", label: "Gambia" },
    { value: "Georgia", label: "Georgia" },
    { value: "Ghana", label: "Ghana" },
    { value: "Greece", label: "Greece" },
    { value: "Grenada", label: "Grenada" },
    { value: "Guatemala", label: "Guatemala" },
    { value: "Guinea", label: "Guinea" },
    { value: "Guinea-Bissau", label: "Guinea-Bissau" },
    { value: "Guyana", label: "Guyana" },
    { value: "Haiti", label: "Haiti" },
    { value: "Holy See (Vatican City)", label: "Holy See (Vatican City)" },
    { value: "Honduras", label: "Honduras" },
    { value: "Hungary", label: "Hungary" },
    { value: "Iceland", label: "Iceland" },
    { value: "India", label: "India" },
    { value: "Indonesia", label: "Indonesia" },
    { value: "Iran", label: "Iran" },
    { value: "Iraq", label: "Iraq" },
    { value: "Ireland", label: "Ireland" },
    { value: "Israel", label: "Israel" },
    { value: "Jamaica", label: "Jamaica" },
    { value: "Japan", label: "Japan" },
    { value: "Jordan", label: "Jordan" },
    { value: "Kazakhstan", label: "Kazakhstan" },
    { value: "Kenya", label: "Kenya" },
    { value: "Kiribati", label: "Kiribati" },
    { value: "Kosovo", label: "Kosovo" },
    { value: "Kuwait", label: "Kuwait" },
    { value: "Kyrgyzstan", label: "Kyrgyzstan" },
    { value: "Laos", label: "Laos" },
    { value: "Latvia", label: "Latvia" },
    { value: "Lebanon", label: "Lebanon" },
    { value: "Lesotho", label: "Lesotho" },
    { value: "Liberia", label: "Liberia" },
    { value: "Libya", label: "Libya" },
    { value: "Liechtenstein", label: "Liechtenstein" },
    { value: "Lithuania", label: "Lithuania" },
    { value: "Luxembourg", label: "Luxembourg" },
    { value: "Madagascar", label: "Madagascar" },
    { value: "Malawi", label: "Malawi" },
    { value: "Malaysia", label: "Malaysia" },
    { value: "Maldives", label: "Maldives" },
    { value: "Mali", label: "Mali" },
    { value: "Malta", label: "Malta" },
    { value: "Marshall Islands", label: "Marshall Islands" },
    { value: "Mauritania", label: "Mauritania" },
    { value: "Mauritius", label: "Mauritius" },
    { value: "Mexico", label: "Mexico" },
    { value: "Micronesia", label: "Micronesia" },
    { value: "Moldova", label: "Moldova" },
    { value: "Monaco", label: "Monaco" },
    { value: "Mongolia", label: "Mongolia" },
    { value: "Montenegro", label: "Montenegro" },
    { value: "Morocco", label: "Morocco" },
    { value: "Mozambique", label: "Mozambique" },
    { value: "Myanmar (Burma)", label: "Myanmar (Burma)" },
    { value: "Namibia", label: "Namibia" },
    { value: "Nauru", label: "Nauru" },
    { value: "Nepal", label: "Nepal" },
    { value: "Netherlands", label: "Netherlands" },
    { value: "New Zealand", label: "New Zealand" },
    { value: "Nicaragua", label: "Nicaragua" },
    { value: "Niger", label: "Niger" },
    { value: "Nigeria", label: "Nigeria" },
    { value: "North Korea", label: "North Korea" },
    { value: "North Macedonia", label: "North Macedonia" },
    { value: "Norway", label: "Norway" },
    { value: "Oman", label: "Oman" },
    { value: "Pakistan", label: "Pakistan" },
    { value: "Palau", label: "Palau" },
    { value: "Palestine, State of", label: "Palestine, State of" },
    { value: "Panama", label: "Panama" },
    { value: "Papua New Guinea", label: "Papua New Guinea" },
    { value: "Paraguay", label: "Paraguay" },
    { value: "Peru", label: "Peru" },
    { value: "Philippines", label: "Philippines" },
    { value: "Poland", label: "Poland" },
    { value: "Portugal", label: "Portugal" },
    { value: "Qatar", label: "Qatar" },
    { value: "Romania", label: "Romania" },
    { value: "Russia", label: "Russia" },
    { value: "Rwanda", label: "Rwanda" },
    { value: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis" },
    { value: "Saint Lucia", label: "Saint Lucia" },
    { value: "Saint Vincent and the Grenadines", label: "Saint Vincent and the Grenadines" },
    { value: "Samoa", label: "Samoa" },
    { value: "San Marino", label: "San Marino" },
    { value: "Sao Tome and Principe", label: "Sao Tome and Principe" },
    { value: "Saudi Arabia", label: "Saudi Arabia" },
    { value: "Senegal", label: "Senegal" },
    { value: "Serbia", label: "Serbia" },
    { value: "Seychelles", label: "Seychelles" },
    { value: "Sierra Leone", label: "Sierra Leone" },
    { value: "Singapore", label: "Singapore" },
    { value: "Slovakia", label: "Slovakia" },
    { value: "Slovenia", label: "Slovenia" },
    { value: "Solomon Islands", label: "Solomon Islands" },
    { value: "Somalia", label: "Somalia" },
    { value: "South Africa", label: "South Africa" },
    { value: "South Korea", label: "South Korea" },
    { value: "South Sudan", label: "South Sudan" },
    { value: "Spain", label: "Spain" },
    { value: "Sri Lanka", label: "Sri Lanka" },
    { value: "Sudan", label: "Sudan" },
    { value: "Suriname", label: "Suriname" },
    { value: "Sweden", label: "Sweden" },
    { value: "Syria", label: "Syria" },
    { value: "Taiwan", label: "Taiwan" },
    { value: "Tajikistan", label: "Tajikistan" },
    { value: "Tanzania", label: "Tanzania" },
    { value: "Thailand", label: "Thailand" },
    { value: "Timor-Leste", label: "Timor-Leste" },
    { value: "Togo", label: "Togo" },
    { value: "Tonga", label: "Tonga" },
    { value: "Trinidad and Tobago", label: "Trinidad and Tobago" },
    { value: "Tunisia", label: "Tunisia" },
    { value: "Turkey", label: "Turkey" },
    { value: "Turkmenistan", label: "Turkmenistan" },
    { value: "Tuvalu", label: "Tuvalu" },
    { value: "Uganda", label: "Uganda" },
    { value: "Ukraine", label: "Ukraine" },
    { value: "United Arab Emirates", label: "United Arab Emirates" },
    { value: "UK", label: "UK" },
    { value: "USA", label: "USA" },
    { value: "Uruguay", label: "Uruguay" },
    { value: "Uzbekistan", label: "Uzbekistan" },
    { value: "Vanuatu", label: "Vanuatu" },
    { value: "Venezuela", label: "Venezuela" },
    { value: "Vietnam", label: "Vietnam" },
    { value: "Yemen", label: "Yemen" },
    { value: "Zambia", label: "Zambia" },
    { value: "Zimbabwe", label: "Zimbabwe" }
];

export const GENERAL_FIELD_OPTIONS = [
  { value: "", label: "Please Select" },
  { value: "Arts and Design", label: "Arts and Design" },
  { value: "Business and Economics", label: "Business and Economics" },
  { value: "Education", label: "Education" },
  { value: "Engineering", label: "Engineering" },
  { value: "Environmental Studies and Agriculture", label: "Environmental Studies and Agriculture" },
  { value: "Humanities", label: "Humanities" },
  { value: "Law and Legal Studies", label: "Law and Legal Studies" },
  { value: "Mathematics", label: "Mathematics" },
  { value: "Medical and Health Sciences", label: "Medical and Health Sciences" },
  { value: "Music", label: "Music" },
  { value: "Science", label: "Science (Natural/Life)" },
  { value: "Social Sciences", label: "Social Sciences" },
  { value: "Technology / IT", label: "Technology / IT" },
  { value: "Other", label: "Other (Not Listed)" }
];

export const DEGREE_TYPE_OPTIONS = [
  { value: "", label: "Please Select" },
  // High School / Secondary Education
  { value: "High School Diploma", label: "High School Diploma" },
  { value: "A-Levels", label: "A-Levels (UK)" },
  { value: "International Baccalaureate", label: "International Baccalaureate (IB)" },
  { value: "Matura", label: "Matura / Maturità" },
  { value: "Abitur", label: "Abitur (Germany)" },
  { value: "Baccalauréat", label: "Baccalauréat (France)" },
  { value: "European Baccalaureate", label: "European Baccalaureate" },
  // Associate Degrees
  { value: "AA", label: "AA (Associate of Arts)" },
  { value: "AS", label: "AS (Associate of Science)" },
  { value: "AAS", label: "AAS (Associate of Applied Science)" },
  // Bachelor's Degrees
  { value: "BSc", label: "BSc (Bachelor of Science)" },
  { value: "BA", label: "BA (Bachelor of Arts)" },
  // Master's Degrees
  { value: "MSc", label: "MSc (Master of Science)" },
  { value: "MA", label: "MA (Master of Arts)" },
  { value: "MAS", label: "MAS (Master Advanced Studies)" },
  { value: "MBA", label: "MBA (Master of Business Administration)" },
  // Doctoral
  { value: "PhD", label: "PhD (Doctorate)" },
  // Professional Certificates
  { value: "Certificate", label: "Certificate / Professional Certificate" },
  // Swiss-Specific Certifications
  { value: "CAS", label: "CAS (Certificate Advanced Studies)" },
  { value: "DAS", label: "DAS (Diploma Advanced Studies)" },
  { value: "Federal Diploma", label: "Federal Diploma (Eidg. Diplom)" }
];

export const GRADE_OPTIONS = [
  { value: "", label: "Select if applicable" },
  { value: "4-4.5", label: "4.0 - 4.5" },
  { value: "4.5-5", label: "4.5 - 5.0" },
  { value: "5-5.5", label: "5.0 - 5.5" },
  { value: "5.5-6", label: "5.5 - 6.0" },
];

// --- Experience Related ---
export const POSITION_TYPE_OPTIONS = [
  { value: "", label: "Please Select" },
  { value: "Full-time", label: "Full-time" },
  { value: "Part-time", label: "Part-time" },
  { value: "Internship", label: "Internship" },
  { value: "Working Student", label: "Working Student" },
  { value: "Freelance / Contractor", label: "Freelance / Contractor" },
  { value: "Apprenticeship", label: "Apprenticeship" },
];

export const YEARS_OF_EXPERIENCE_OPTIONS = [
  { value: "", label: "Please Select" },
  { value: "no-experience", label: "No professional experience yet" },
  { value: "less-than-1", label: "Less than 1 year" },
  { value: "1-2", label: "1-2 years" },
  { value: "3-5", label: "3-5 years" },
  { value: "6-10", label: "6-10 years" },
  { value: "11-15", label: "11-15 years" },
  { value: "16-20", label: "16-20 years" },
  { value: "more-than-20", label: "More than 20 years" },
];

// --- Skills Related ---
export const LANGUAGE_PROFICIENCY_OPTIONS = [
  { value: "", label: "Choose Level" },
  { value: "None", label: "None" },
  { value: "Beginner", label: "Beginner (A1-A2)" },
  { value: "Intermediate", label: "Intermediate (B1-B2)" },
  { value: "Advanced", label: "Advanced (C1)" },
  { value: "Fluent", label: "Fluent (C2)" },
  { value: "Native", label: "Native" },
];

export const SKILL_PROFICIENCY_OPTIONS = [
    { value: "", label: "Select proficiency" },
    { value: "Beginner", label: "Beginner - Basic knowledge, need guidance" },
    { value: "Intermediate", label: "Intermediate - Working knowledge, occasional assistance" },
    { value: "Advanced", label: "Advanced - Comprehensive knowledge, work independently" },
    { value: "Expert", label: "Expert - Deep knowledge, can teach others" },
    { value: "Professional", label: "Professional - Mastery level, recognized authority" },
];

// --- Preferences Related ---
export const DURATION_OPTIONS = [
    { value: "", label: "Please Select" },
    { value: "0-3 months", label: "0-3 months" },
    { value: "3-6 months", label: "3-6 months" },
    { value: "6-12 months", label: "6-12 months" },
    { value: "12+ months", label: "12+ months" },
];

export const JOB_TYPE_OPTIONS = ['Internship', 'Part-time', 'Career Starter (full-time)'];

export const LOCATION_OPTIONS = [
    { value: "AG",   label: "Aargau (AG)" },
    { value: "AR/AI", label: "Appenzell (AR/AI)" },
    { value: "BS/BL", label: "Basel (BS/BL)" },
    { value: "BE",   label: "Bern / Berne (BE)" },
    { value: "FR",   label: "Freiburg / Fribourg (FR)" },
    { value: "GE",   label: "Genève (GE)" },
    { value: "GL",   label: "Glarus (GL)" },
    { value: "GR",   label: "Graubünden (GR)" },
    { value: "JU",   label: "Jura (JU)" },
    { value: "LU",   label: "Luzern (LU)" },
    { value: "NE",   label: "Neuchâtel (NE)" },
    { value: "NW/OW",label: "Unterwalden (NW/OW)" },
    { value: "SH",   label: "Schaffhausen (SH)" },
    { value: "SZ",   label: "Schwyz (SZ)" },
    { value: "SO",   label: "Solothurn (SO)" },
    { value: "SG",   label: "St. Gallen (SG)" },
    { value: "TG",   label: "Thurgau (TG)" },
    { value: "TI",   label: "Ticino (TI)" },
    { value: "UR",   label: "Uri (UR)" },
    { value: "VS",   label: "Valais / Wallis (VS)" },
    { value: "VD",   label: "Vaud (VD)" },
    { value: "ZG",   label: "Zug (ZG)" },
    { value: "ZH",   label: "Zürich (ZH)" },
    { value: "Other", label: "Other (Specify Below)" }
];

export const INDUSTRY_PREFERENCE_OPTIONS = [
    { value: "Finance",          label: "Finance" },
    { value: "Marketing",        label: "Marketing" },
    { value: "Consulting",       label: "Management Consulting" },
    { value: "HR",               label: "Human Resources (HR)" },
    { value: "Sales",            label: "Sales & Business Development" },
    { value: "MechEng",          label: "Mechanical Engineering" },
    { value: "CivilEng",         label: "Civil Engineering" },
    { value: "ElecEng",          label: "Electrical Engineering" },
    { value: "SoftEng",          label: "Software Engineering" },
    { value: "AeroEng",          label: "Aerospace Engineering" },
    { value: "SoftDev",          label: "Software Development" },
    { value: "Cyber",            label: "Cybersecurity" },
    { value: "DataAI",           label: "Data Science & AI" },
    { value: "UXUI",             label: "UX/UI Design" },
    { value: "Cloud",            label: "Cloud Computing" },
    { value: "Clinical",         label: "Clinical Internships" },
    { value: "PublicHealth",     label: "Public Health" },
    { value: "BioPharma",        label: "Biotechnology/Pharmaceuticals" },
    { value: "MedTech",          label: "Medical Technology" },
    { value: "GraphicDesign",    label: "Graphic Design" },
    { value: "FilmVideo",        label: "Film & Video Production" },
    { value: "Journalism",       label: "Journalism & Writing" },
    { value: "PR",               label: "Public Relations (PR)" },
    { value: "Advertising",      label: "Advertising" },
    { value: "EnvSci",           label: "Environmental Science" },
    { value: "Sustainability",   label: "Sustainability Consulting" },
    { value: "AgriForest",       label: "Agriculture & Forestry" },
    { value: "Renewable",        label: "Renewable Energy" },
    { value: "Legal",            label: "Legal Internships" },
    { value: "GovPolicy",        label: "Government & Public Policy" },
    { value: "Nonprofit",        label: "Nonprofit & Advocacy" },
    { value: "Teaching",         label: "Teaching" },
    { value: "SocialWork",       label: "Social Work" },
    { value: "Counseling",       label: "Counseling & Therapy" },
    { value: "EarlyEdu",         label: "Early Childhood Education" },
    { value: "HotelMgmt",        label: "Hotel Management" },
    { value: "EventPlan",        label: "Event Planning & Coordination" },
    { value: "Tourism",          label: "Tourism Marketing" },
    { value: "Ecommerce",        label: "E-commerce Operations" },
    { value: "RetailMarket",     label: "Retail Marketing" },
    { value: "CustomerService",  label: "Customer Service" },
    { value: "BrandPartner",     label: "Brand Partnerships & Licensing" }
];

// --- Functional Expertise (Commodities/Energy/Finance Focus) ---
// These categories are specific to SetSelect talent pool
export const FUNCTIONAL_EXPERTISE_OPTIONS = [
  'Trading',
  'Risk Management',
  'Quantitative Analysis',
  'Technology',
  'Operations',
  'Finance',
  'Leadership',
  'Legal',
  'Compliance',
  'Research',
  'Analytics',
  'Engineering'
  // Note: 'Other' is handled by user input, not by parser extraction
];